# Generated by Django 4.2.11 on 2024-04-15 12:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RecognitionData",
            fields=[
                (
                    "id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "data_recognition",
                    models.BinaryField(null=True, verbose_name="Запись голоса"),
                ),
                (
                    "word_for_check",
                    models.TextField(null=True, verbose_name="Слово для проверки"),
                ),
                (
                    "transcription_word",
                    models.TextField(null=True, verbose_name="Слово транскрибации"),
                ),
                (
                    "date_recoding",
                    models.DateField(null=True, verbose_name="Дата записи"),
                ),
                ("wer", models.FloatField(null=True, verbose_name="WER")),
                ("cer", models.FloatField(null=True, verbose_name="CER")),
                ("mer", models.FloatField(null=True, verbose_name="MER")),
                ("wil", models.FloatField(null=True, verbose_name="WIL")),
                ("iwer", models.FloatField(null=True, verbose_name="IWER")),
            ],
            options={
                "verbose_name": "Распознавание речи",
                "db_table": "recognition_data",
            },
        ),
        migrations.CreateModel(
            name="SynthesisData",
            fields=[
                (
                    "id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "data_recognition",
                    models.BinaryField(null=True, verbose_name="Синтез речи"),
                ),
                (
                    "word_synthesis",
                    models.TextField(null=True, verbose_name="Слово синтеза"),
                ),
                (
                    "word_input",
                    models.TextField(null=True, verbose_name="Введенное слово"),
                ),
                (
                    "date_synthesis",
                    models.DateField(null=True, verbose_name="Дата синтеза"),
                ),
                ("wer", models.FloatField(null=True, verbose_name="WER")),
            ],
            options={
                "verbose_name": "Синтез речи",
                "db_table": "synthesis_data",
            },
        ),
        migrations.CreateModel(
            name="Text",
            fields=[
                (
                    "id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("theme", models.TextField(verbose_name="Тема")),
                ("text", models.TextField(verbose_name="Текст")),
                ("date_text", models.DateField(verbose_name="Дата текста")),
            ],
            options={
                "verbose_name": "Текст",
                "db_table": "text",
            },
        ),
        migrations.CreateModel(
            name="DataRecognitionAndSynthesis",
            fields=[
                (
                    "id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "sequence_number",
                    models.IntegerField(verbose_name="Порядковый номер"),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Клиент",
                    ),
                ),
                (
                    "recognition_data",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="async_transcription_and_speech_synthesis.recognitiondata",
                        verbose_name="Данные распознавания",
                    ),
                ),
                (
                    "synthesis_data",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="async_transcription_and_speech_synthesis.synthesisdata",
                        verbose_name="Данные синтеза",
                    ),
                ),
                (
                    "text",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="async_transcription_and_speech_synthesis.text",
                        verbose_name="Текст",
                    ),
                ),
            ],
            options={
                "verbose_name": "Данные распознавания и синтеза речи",
                "db_table": "data_recognition_and_synthesis",
            },
        ),
    ]
