# Generated by Django 4.2.11 on 2024-04-15 12:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("async_transcription_and_speech_synthesis", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Recommendation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "recommendation_type",
                    models.TextField(null=True, verbose_name="Тип рекомендации"),
                ),
                (
                    "recommendation_text_by_llm",
                    models.TextField(
                        null=True, verbose_name="Текст рекомендации (LLM)"
                    ),
                ),
                (
                    "recommendation_text_by_logopedist",
                    models.TextField(
                        null=True, verbose_name="Текст рекомендации (логопед)"
                    ),
                ),
                (
                    "date_recommendation",
                    models.DateField(null=True, verbose_name="Дата рекомендации"),
                ),
                (
                    "data_recognition_and_synthesis",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="async_transcription_and_speech_synthesis.datarecognitionandsynthesis",
                        verbose_name="Данные распознавания и синтеза",
                    ),
                ),
                (
                    "logopedist",
                    models.ForeignKey(
                        limit_choices_to={"is_moderator": True},
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Логопед",
                    ),
                ),
            ],
            options={
                "verbose_name": "Рекомендация",
                "db_table": "recommendation",
            },
        ),
    ]
